### ISSUE TITLE
Add List support in ConfigProvider service

### ISSUE THREAD

**Issue by daneshk** [wso2/carbon-config#17]
Current ConfigProvider service only support to return configuration bean object and configuration Map. according to below example, we are expecting List instead to Map. We need to add List support to cater the requirement.

````yaml
  # Data Sources Configuration
wso2.datasources:
  - name: WSO2_CARBON_DB
    description: The datasource used for registry and user manager
      # JNDI mapping of a data source
    jndiConfig:
        # JNDI name
        # THIS IS A MANDATORY FIELD
      name: jdbc/WSO2CarbonDB/test
        # JNDI Reference Flag
      useJndiReference: false
````
