### ISSUE TITLE
Change Environment Variable definition

### ISSUE THREAD

**Issue by tharindu1st** [wso2/carbon-config#66]
**Description:**
In order to define an environment variable for name config value under complexBean, we have to defind environment variable as follows.
```bash
WSO2.CONFIGURATION_COMPLEXTESTBEAN_NAME="default"
```
As OS its not support to keep (.) mark in the environment variable due to that we had convert it to( _ ) in the namespace.

current configuration as follows
```bash
WSO2_CONFIGURATION_COMPLEXTESTBEAN_NAME="default"
```

  
```yaml
wso2.configuration:
  complexBean:
    name: default
    Bean:
      name: default
```
